packages:
  - packages/*
  - slides/*

catalog:
  '@antfu/eslint-config': ^7.2.0
  '@slidev/cli': ^52.11.5
  '@slidev/client': ^52.11.5
  '@slidev/theme-default': ^0.25.0
  '@slidev/theme-seriph': ^0.25.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - playwright-chromium
